//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_2690
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Class2.
    /// </summary>
    // *** Start programmer edit section *** (Class2 CustomAttributes)

    // *** End programmer edit section *** (Class2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Class2E", new string[] {
            "Per21 as \'Per21\'",
            "Per22 as \'Per22\'"})]
    [View("Class2L", new string[] {
            "Per21 as \'Per21\'",
            "Per22 as \'Per22\'"})]
    public class Class2 : ICSSoft.STORMNET.DataObject
    {
        
        private string fPer21;
        
        private string fPer22;
        
        // *** Start programmer edit section *** (Class2 CustomMembers)

        // *** End programmer edit section *** (Class2 CustomMembers)

        
        /// <summary>
        /// Per21.
        /// </summary>
        // *** Start programmer edit section *** (Class2.Per21 CustomAttributes)

        // *** End programmer edit section *** (Class2.Per21 CustomAttributes)
        [StrLen(255)]
        public virtual string Per21
        {
            get
            {
                // *** Start programmer edit section *** (Class2.Per21 Get start)

                // *** End programmer edit section *** (Class2.Per21 Get start)
                string result = this.fPer21;
                // *** Start programmer edit section *** (Class2.Per21 Get end)

                // *** End programmer edit section *** (Class2.Per21 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class2.Per21 Set start)

                // *** End programmer edit section *** (Class2.Per21 Set start)
                this.fPer21 = value;
                // *** Start programmer edit section *** (Class2.Per21 Set end)

                // *** End programmer edit section *** (Class2.Per21 Set end)
            }
        }
        
        /// <summary>
        /// Per22.
        /// </summary>
        // *** Start programmer edit section *** (Class2.Per22 CustomAttributes)

        // *** End programmer edit section *** (Class2.Per22 CustomAttributes)
        [StrLen(255)]
        public virtual string Per22
        {
            get
            {
                // *** Start programmer edit section *** (Class2.Per22 Get start)

                // *** End programmer edit section *** (Class2.Per22 Get start)
                string result = this.fPer22;
                // *** Start programmer edit section *** (Class2.Per22 Get end)

                // *** End programmer edit section *** (Class2.Per22 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class2.Per22 Set start)

                // *** End programmer edit section *** (Class2.Per22 Set start)
                this.fPer22 = value;
                // *** Start programmer edit section *** (Class2.Per22 Set end)

                // *** End programmer edit section *** (Class2.Per22 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Class2E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Class2E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Class2E", typeof(IIS.Product_2690.Class2));
                }
            }
            
            /// <summary>
            /// "Class2L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Class2L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Class2L", typeof(IIS.Product_2690.Class2));
                }
            }
        }
    }
}
