//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_2690
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Class1.
    /// </summary>
    // *** Start programmer edit section *** (Class1 CustomAttributes)

    // *** End programmer edit section *** (Class1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Class1E", new string[] {
            "Per11 as \'Пер11\'",
            "Per12 as \'Пер12\'",
            "Class2 as \'Класс2\'",
            "Class2.Per21 as \'Пер21\'",
            "Class2.Per22 as \'Пер22\'"})]
    [View("Class1L", new string[] {
            "Per11 as \'Per11\'",
            "Per12 as \'Per12\'",
            "Class2",
            "Class2.Per21 as \'Per21\'"})]
    public class Class1 : ICSSoft.STORMNET.DataObject
    {
        
        private string fPer11;
        
        private string fPer12;
        
        private IIS.Product_2690.Class2 fClass2;
        
        // *** Start programmer edit section *** (Class1 CustomMembers)

        // *** End programmer edit section *** (Class1 CustomMembers)

        
        /// <summary>
        /// Per11.
        /// </summary>
        // *** Start programmer edit section *** (Class1.Per11 CustomAttributes)

        // *** End programmer edit section *** (Class1.Per11 CustomAttributes)
        [StrLen(255)]
        public virtual string Per11
        {
            get
            {
                // *** Start programmer edit section *** (Class1.Per11 Get start)

                // *** End programmer edit section *** (Class1.Per11 Get start)
                string result = this.fPer11;
                // *** Start programmer edit section *** (Class1.Per11 Get end)

                // *** End programmer edit section *** (Class1.Per11 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class1.Per11 Set start)

                // *** End programmer edit section *** (Class1.Per11 Set start)
                this.fPer11 = value;
                // *** Start programmer edit section *** (Class1.Per11 Set end)

                // *** End programmer edit section *** (Class1.Per11 Set end)
            }
        }
        
        /// <summary>
        /// Per12.
        /// </summary>
        // *** Start programmer edit section *** (Class1.Per12 CustomAttributes)

        // *** End programmer edit section *** (Class1.Per12 CustomAttributes)
        [StrLen(255)]
        public virtual string Per12
        {
            get
            {
                // *** Start programmer edit section *** (Class1.Per12 Get start)

                // *** End programmer edit section *** (Class1.Per12 Get start)
                string result = this.fPer12;
                // *** Start programmer edit section *** (Class1.Per12 Get end)

                // *** End programmer edit section *** (Class1.Per12 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class1.Per12 Set start)

                // *** End programmer edit section *** (Class1.Per12 Set start)
                this.fPer12 = value;
                // *** Start programmer edit section *** (Class1.Per12 Set end)

                // *** End programmer edit section *** (Class1.Per12 Set end)
            }
        }
        
        /// <summary>
        /// Class1.
        /// </summary>
        // *** Start programmer edit section *** (Class1.Class2 CustomAttributes)

        // *** End programmer edit section *** (Class1.Class2 CustomAttributes)
        [PropertyStorage(new string[] {
                "Class2"})]
        public virtual IIS.Product_2690.Class2 Class2
        {
            get
            {
                // *** Start programmer edit section *** (Class1.Class2 Get start)

                // *** End programmer edit section *** (Class1.Class2 Get start)
                IIS.Product_2690.Class2 result = this.fClass2;
                // *** Start programmer edit section *** (Class1.Class2 Get end)

                // *** End programmer edit section *** (Class1.Class2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class1.Class2 Set start)

                // *** End programmer edit section *** (Class1.Class2 Set start)
                this.fClass2 = value;
                // *** Start programmer edit section *** (Class1.Class2 Set end)

                // *** End programmer edit section *** (Class1.Class2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Class1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Class1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Class1E", typeof(IIS.Product_2690.Class1));
                }
            }
            
            /// <summary>
            /// "Class1L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Class1L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Class1L", typeof(IIS.Product_2690.Class1));
                }
            }
        }
    }
}
